# docker-compose.yml
version: "3"

services:
  redis:
    image: "redis:5.0.8"
    ports:
      - "6379:6379"
  zookeeper:
    image: "zookeeper:3.6.0"
    ports:
      - "2181:2181"
  kafka:
    image: "wurstmeister/kafka:2.12-2.4.1"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  mongodb:
    image: "mongo:3.6.17"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: "coffee-bean"
    volumes:
      - mongodb:/data/db/
  frontend:
    image: "node:14.0.0"
    user: "node"
    environment:
      NODE_ENV: "development"
    working_dir: /home/node/app/frontend/
    volumes:
      - .:/home/node/app/
      - ./node_modules/:/home/node/app/node_modules/:ro
    command: "npm run build-watch"
  backend-fileServer:
    image: "node:14.0.0"
    ports:
      - "4080:4080"
      - "4443:4443"
    depends_on:
      - frontend
    environment:
      NODE_ENV: "development"
#      GATEWAY_HOST: "backend-gateway"
#      GATEWAY_HTTP_PORT: "5000"
#      GATEWAY_HTTPS_PORT: "5443"
    working_dir: /home/node/app/backend/fileServer/
    volumes:
      - .:/home/node/app/:ro
      - ./node_modules/:/home/node/app/node_modules/:ro
    command: "npm run start-watch"
  backend-websocket:
    image: "node:14.0.0"
    ports:
      - "5080:5080"
      - "5443:5443"
    environment:
      NODE_ENV: "development"
#      GATEWAY_HOST: "backend-gateway"
#      GATEWAY_HTTP_PORT: "5000"
#      GATEWAY_HTTPS_PORT: "5443"
    working_dir: /home/node/app/backend/websocket/
    volumes:
      - .:/home/node/app/:ro
      - ./node_modules/:/home/node/app/node_modules/:ro
    command: "npm run start-watch"
  backend-api:
    image: "node:14.0.0"
    ports:
      - "6080:6080"
      - "6443:6443"
    depends_on:
      - redis
      - kafka
      - mongodb
    environment:
      NODE_ENV: "development"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      KAFKA_HOST: "kafka"
      KAFKA_PORT: "9092"
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: "27017"
#      GATEWAY_HOST: "backend-gateway"
#      GATEWAY_HTTP_PORT: "5000"
#      GATEWAY_HTTPS_PORT: "5443"
    working_dir: /home/node/app/backend/api/
    volumes:
      - .:/home/node/app/:ro
      - ./node_modules/:/home/node/app/node_modules/:ro
    command: "npm run start-watch"
#  backend-gateway:
#    image: "node:14.0.0"
#    ports:
#      - "5000:5000"
#      - "5443:5443"
#    depends_on:
#      - backend-api
#      - backend-fileServer
#    environment:
#      NODE_ENV: "development"
#      API_HOST: "backend-api"
#      API_HTTP_PORT: "6000"
#      API_HTTPS_PORT: "6443"
#      FILESERVER_HOST: "backend-fileServer"
#      FILESERVER_HTTP_PORT: "4000"
#      FILESERVER_HTTPS_PORT: "4443"
#    working_dir: /home/node/app/backend/gateway/
#    volumes:
#      - .:/home/node/app/:ro
#      - ./node_modules/:/home/node/app/node_modules/:ro
#    command: "npm run start-watch"

volumes:
  mongodb:
