export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_CLEAR = 'CART_CLEAR';

export const ORDER_FETCH_ORDERS = 'ORDER_FETCH_ORDERS';
export const ORDER_FETCH_ORDER = 'ORDER_FETCH_ORDER';

export const USER_SET_EMAIL = 'USER_SET_EMAIL';
export const USER_SET_PASSWORD = 'USER_SET_PASSWORD';
export const USER_SET_ISLOGGEDIN = 'USER_SET_ISLOGGEDIN';
